---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: probe
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/manspace80/k8s-argocd-bootstrap.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  syncWindows:
    - kind: allow
      schedule: "* * * * *"
      duration: "2m"
